<?php 
	require_once( 'functions/function.php'); 
	$oPageContents->get_header(); 
	$oPageContents->get_nav(); 
?>
<section>
	<div class="full" id="courseBanner">
		<div class="container">
            <h1 class="bnrHdr" id="link">3D ANIMATION</h1>
			<p class="bnrTxt">It all starts with the fundamentals</p>
		</div>
		<div class="container pd0">
			<div class="bnrBdr"></div>
		</div>
	</div>
	<!--container end-->
</section>
<!--banner part end-->
<?php
	$oPageContents->get_part('course_nav.php');
?>
<section>
	<div class="container pd0 courseDet">
        <div class="col-md-12 pd0">
            <div class="col-md-3 col-sm-3 pd0">
                <?php $oPageContents->get_part('course_nav_sidebar.php'); ?>
            </div>
            <div class="col-md-9 col-sm-9 pd0 crsHead">
                <p class="col-md-10"><b>3D</b> ANIMATION</p>
                <img src="images/course/crs3d.jpg" alt="Graphics" class="img-responsive">
            </div>
        </div>
	</div>
	<div class="container pd0">
		<div class="col-md-3  crsall col-sm-3 pd0">
			<h2>student's work</h2>
			<img class="img-responsive" src="images/course/crsdet01.jpg" alt="">
			<h2>student's feedback</h2>
			<div class="crsfb">
				<p class="fa fa-quote-left"></p>
				<p>
					It was a great opportunity for the student to work together on some common goals. The training was a valuable first step toward becoming a growth generation.
				</p>
				<img class="img-responsive" src="images/course/fb01.jpg" alt="">
				<p class="cdt01">Md. Anowarul Islam</p>
				<p class="cdt02">
					Digital Designer & Content Executive Multimode Ltd.
				</p>
			</div>
			<img class="img-responsive" src="images/course/pearson.jpg" alt="">
			<div class="crsfb01">
				<img class="img-responsive" src="images/course/phn_c.png" alt="">
				<p class="crsMi">
					MORE INFORMATION?
				</p>
				<p class="crsCu">
					Call us
                    <br><span>+880 1624666000, +880 1624888444</span>
				</p>
			</div>
		</div>
		<div class="col-md-9 col-sm-9 crsDes">
			<h4>Overview</h4>
			<p>
               Animation is referred to a visual technique. It’s also called an illusion generated by rapid changing of a series of images, each off course slightly different from the last. Each image requires a small change such as leg moves or wheel of car turns. When all the images are viewed in a same frame rapidly then our eyes fills all the gaps and illusion of movement is complete.<br><br> 
			   We offer student the 3D Animation Course leads students through the methods and techniques of animating virtual objects and environments using industry-leading software and hardware. In this course, students are introduced to the principles of animating three-dimensional computer graphics. 
            </p>
			<div class="col-sm-12 pd0">
			<div class="col-sm-6 pd0">
				<h4>modules</h4>
				<ul>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">Computer Application and Multimedia</li>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">Concept of Multimedia Presentation</li>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">PowerPoint Interactive Presentation</li>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">Image Editing With Photoshop</li>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">Visualization Technique</li>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">AD Analyses</li>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">Managing Media Element</li>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">Visualization Technique</li>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">Digital Drawing with Illustration</li>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">Internet Technology</li>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">Color Studies</li>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">Publishing Makeup with InDesign</li>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">Flash Animation</li>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">Project</li>
				</ul>
			</div>
			<div class="col-sm-6 pd0">
				<h4>Software Taught</h4>
				<ul>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">Auto Cad 3D</li>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">3Ds Max Advance</li>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">Lumion</li>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">Adobe Premiere</li>
					<li>
						<img src="images/ftr_list-bullet2.png" alt="bullet">After Effects</li>
				</ul>
			</div>
			</div>
			<div class="col-sm-12 pd0 crsHiLs">
				<h4>Highlight</h4>
                <ul>
                    <li>
                        <img src="images/tik.png" alt="bullet">
                         Drawing & Perspective of 3D Modeling 
                    </li>
                    <li>
                        <img src="images/tik.png" alt="bullet">
                        Light, Colour & Design 
                    </li>
                    <li>
                        <img src="images/tik.png" alt="bullet">
                        History of Film & Animation 
                    </li>
                    <li>
                        <img src="images/tik.png" alt="bullet">
                         Principles of Animation                    
                      </li>
                    <li>
                        <img src="images/tik.png" alt="bullet">
                        Storytelling & Scriptwriting 
                    </li>
                    <li>
                        <img src="images/tik.png" alt="bullet">
                        Fundamentals for Creative Professionals 
                    </li>
                    <li>
                        <img src="images/tik.png" alt="bullet">
                        Idea Jumpstart                     
                       </li>
                    <li>
                        <img src="images/tik.png" alt="bullet">
                         Sports & Wellness                     
                    </li>
                    <li>
                        <img src="images/tik.png" alt="bullet">
                        Figure Drawing 
                    </li>
                    <li>
                        <img src="images/tik.png" alt="bullet">
                        Practical application using latest versions of tools / software like Auto Cad, 3Ds Max, V-ray, Adobe Premiere. 
                    </li>
                    <li>
                        <img src="images/tik.png" alt="bullet">
                        Hands-on training using latest tools &techniques 
                    </li>
                     <li>
                        <img src="images/tik.png" alt="bullet">
                        Specialization & creating portfolio in the area of interest  
                    </li>
                     <li>
                        <img src="images/tik.png" alt="bullet">
                        Industry-relevant curriculum  
                    </li>
                </ul>
			</div>
            <div class="col-sm-12 pd0">
                <div class="col-sm-4">
                    <h4>Career Support</h4>
                    <p> After course completion, students can get jobs as:</p>
                    <ul>
                        <li>
                            <img src="images/ftr_list-bullet2.png" alt="bullet">3D (Three-Dimensions) Designer</li>
                        <li>
                            <img src="images/ftr_list-bullet2.png" alt="bullet">Special Effects Artiste, Animator</li>
                        <li>
                            <img src="images/ftr_list-bullet2.png" alt="bullet">3D Compositor / Modeler </li>
                        <li>
                            <img src="images/ftr_list-bullet2.png" alt="bullet">Motion Graphic Artist</li>
                        <li>
                            <img src="images/ftr_list-bullet2.png" alt="bullet">Visual Effects Artist</li>
                        <li>
                            <img src="images/ftr_list-bullet2.png" alt="bullet">Game Design Animator</li>
                          <li>
                            <img src="images/ftr_list-bullet2.png" alt="bullet">Shedders</li>
                            <li>
                            <img src="images/ftr_list-bullet2.png" alt="bullet">Modelers</li>
                            <li>
                            <img src="images/ftr_list-bullet2.png" alt="bullet">Bench Animators</li>
                    </ul>
                </div>
                <div class="col-sm-4">
                    <h4>DAY AND TIME</h4>
                    <p>Duration: 4 months <br> (2 hours a day, 2 days a week)</p>
                </div>
                <div class="col-sm-4">
                    <h4>Course Fee:</h4>
                    <p>BDT 30000/-</p>
                </div>
            </div>
            <div class="col-sm-12 pd0 marT20">
                <div class="col-sm-12"><div class="crsbdr"></div></div>
                <div class="col-sm-4">
                    <div class="crsSug text-center">
                        <img class="img-responsive" src="images/webdesign.jpg" alt="webdesign">
                        <h4>web design</h4>
                        <p>Photoshop (Basic), HTML, HTML5, CSS, CSS3, JQuery, JavaScript, Wordpress, PHP (Basic)</p>
                        <a href="webdesign_details.php">Learn more <span class="fa fa-angle-right"></span></a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="crsSug text-center">
                        <img class="img-responsive" src="images/webdev.jpg" alt="webdesign">
                        <h4>WEB DEvelopment</h4>
                        <p>Photoshop (Basic), HTML, HTML5, CSS, CSS3, JQuery, JavaScript, Wordpress, PHP (Basic)</p>
                        <a href="webdevelopment_details.php">Learn more <span class="fa fa-angle-right"></span></a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="crsSug text-center">
                        <img class="img-responsive" src="images/3ddesign.jpg" alt="webdesign">
                        <h4>graphics design</h4>
                        <p>Photoshop (Basic), HTML, HTML5, CSS, CSS3, JQuery, JavaScript, Wordpress, PHP (Basic)</p>
                        <a href="graphics_details.php">Learn more <span class="fa fa-angle-right"></span></a>
                    </div>
                </div>
            </div>
		</div>
	</div>
	<!--courseDet end-->

    <?php $oPageContents->get_part('crs_apply_part.php'); ?>
</section>
<div class="container ptBdr"></div>
<?php $oPageContents->get_part('partner_part.php'); $oPageContents->get_footer(); ?>
<script>
    <?php $oPageContents->fix_course(); ?>
</script>